# Generated by Django 6.0.4 on 2026-05-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimYear',
            fields=[
                ('year_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField(unique=True)),
                ('year_start_date', models.DateField()),
                ('year_end_date', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'dim_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactAnalysis',
            fields=[
                ('analysis_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('analysis_period', models.CharField(max_length=50)),
                ('compounded_sales_growth_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('compounded_profit_growth_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_price_cagr_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roe_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fact_analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactBalanceSheet',
            fields=[
                ('balance_sheet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('share_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reserves_and_surplus', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('long_term_borrowings', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('short_term_borrowings', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('property_plant_equipment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('capital_work_in_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investments', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('inventories', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('trade_receivables', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cash_and_cash_equivalents', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fact_balance_sheet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactCashFlow',
            fields=[
                ('cash_flow_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cash_flow_from_operating_activities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cash_flow_from_investing_activities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cash_flow_from_financing_activities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_increase_in_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('opening_cash_and_cash_equivalents', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('closing_cash_and_cash_equivalents', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fact_cash_flow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactProfitLoss',
            fields=[
                ('profit_loss_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cost_of_materials_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('employee_benefit_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('finance_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('depreciation_and_amortization', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('profit_before_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tax_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('profit_after_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('basic_eps', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('diluted_eps', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fact_profit_loss',
                'managed': False,
            },
        ),
    ]
