# Generated by Django 6.0.4 on 2026-05-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_partner_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimCompany',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('ticker_symbol', models.CharField(max_length=32, unique=True)),
                ('isin', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('nse_symbol', models.CharField(blank=True, max_length=32, null=True)),
                ('bse_code', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'dim_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimSector',
            fields=[
                ('sector_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'dim_sector',
                'managed': False,
            },
        ),
        migrations.RenameIndex(
            model_name='apiusagelog',
            new_name='api_usage_l_partner_af0c1b_idx',
            old_name='api_usage_l_partner_6176db_idx',
        ),
        migrations.RenameIndex(
            model_name='apiusagelog',
            new_name='api_usage_l_endpoin_b0dfcd_idx',
            old_name='api_usage_l_endpoin_148a7e_idx',
        ),
    ]
